### ISSUE TITLE
README needs some flare

### ISSUE THREAD

**Issue by johndbritton** [johndbritton/japan#1]
Maybe a photo of :tokyo_tower:?

@dice @lizclink Do you know of any good photos we can use?

**Comment by lizclink** [comment]
@johndbritton here's one!

![_mg_8823](https://cloud.githubusercontent.com/assets/2566204/8033835/d4ea459e-0e1c-11e5-8d1e-1214043e824f.JPG)

**Comment by lizclink** [comment]
had an inspiration @johndbritton!
![tokyo-tower](https://cloud.githubusercontent.com/assets/2566204/8033916/af115e6a-0e1d-11e5-8b14-de0acd084f8a.jpg)

**Comment by n0bisuke** [comment]
![](http://i.gyazo.com/44ee52958949005beac9f2842cc8f15e.png)
